apiVersion: v1
kind: Service
metadata:
  name: kvstore-api-single
  namespace: kv-part1
  labels:
    app: kvstore-api-single
spec:
  type: LoadBalancer
  selector:
    app: kvstore-api-single
  ports:
    - port: 7000
      targetPort: 7000