apiVersion: v1
kind: Service
metadata:
  name: kvstore-router
  labels:
    app: kvstore-router
spec:
  type: LoadBalancer
  selector:
    app: kvstore-router
  ports:
    - name: http
      port: 7001
      targetPort: 7001