apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvstore-router
  labels:
    app: kvstore-router
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kvstore-router
  template:
    metadata:
      labels:
        app: kvstore-router
    spec:
      containers:
        - name: kvstore-router
          image: ikramulhaqueoli/kvstore-router:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:7001"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: KvStoreApiNodes__Port
              valueFrom:
                configMapKeyRef:
                  name: kvstore-router-config
                  key: KvStoreApiNodes__Port
            - name: KvStoreApiNodes__ReplicaCount
              valueFrom:
                configMapKeyRef:
                  name: kvstore-router-config
                  key: KvStoreApiNodes__ReplicaCount
          readinessProbe:
            httpGet:
              path: /health
              port: 7001
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 7001
            initialDelaySeconds: 5
            periodSeconds: 10
